version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: dev
  ignore:
  - dependency-name: Npgsql.EntityFrameworkCore.PostgreSQL
    versions:
    - 5.0.5
  - dependency-name: Oracle.EntityFrameworkCore
    versions:
    - 5.21.1
